### ISSUE TITLE
    TypeError: Cannot read properties of null (reading 'destroyed')

### ISSUE THREAD

**Issue by iapain** [BackendStack21/fast-proxy-lite#2]
In mocking or some testing environment or when headers are already sent, `socket` might not be  defined or `null`. In that case, we get following:

```
TypeError: Cannot read properties of null (reading 'destroyed')
      at node_modules/fast-proxy-lite/index.js:91:24
      at Immediate.<anonymous> (node_modules/fast-proxy-lite/lib/request.js:40:28)
```

This issue is very specific, I cannot replicate it on macOS but I could replicate it on nodejs docker image (but on v14 and v16.13.2)

**Comment by jkyberneees** [comment]
Hi @iapain, many thanks for taking care of the quality of this project, your contributions are valuable!
I have followed up with a PR to address this issue, can you please have a quick look: https://github.com/BackendStack21/fast-proxy-lite/pull/3

Many thanks!
